language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
script:
  - pytest tests/uts -v
  - pytest tests/integration -v
dist: xenial
before_install:
  - cd tests/integration
  - export TALKER_HOST_ID=MyHostId
  - docker-compose up --no-start
  - docker-compose start
  - docker-compose ps
  - cd ../../
install:
  - pip install .[test]
deploy:
  provider: pypi
  user: wekaio-pypi
  password:
    secure: pAHmETf1y3Dq3SmzgpFlArh3Zs4M8hS09SB+H9QIHgjX8bKCCs0kO0Ll5P5QZZsphY1DD09ueDGQG/pha8Kje4aUae8iuo4dt+Sqpr8ScrqKQgW8aYDKg+hN22QqJugtLgkBe7/FPOjhGPZwGONeWW2b6lfPYgS4bfJNnw71vE2eJcnPi+AjWbmxDzVdusIHh1Q4W1avcpc8drDexLMiMey1r5Mt697OoyQGojhmRdggSZYOszR6ElySyI3lFlsDBPeX3EmpphgSvLC6CDbTZQH/8xEe3dXP9cldPwSEa5r+KeJYJ15CqAkXSZbYWVpL6Fkh8uOuuMkCrrWr8SMQ6XjDMqT80LtqIi0siqgCjZF8PDFT2IyMHr7Ds5kc1Mq4/A3oK/ie/ZF0wPV6StJz/ZGIjw+u23MOFLdmSBjuJ7L7neaMeTxNXoyf3kuRjKGegJzuuGO+6MXd3DjK5XHrPMFhl5hOZrHa8+rdKOJKQZSLKbfUS2QN3tbJ4PMXX3kQFBeLG29ZABenZq5WaF2mcJIAYFJnhsHQxOYmCwHl6uowgU+Gn8fv7I0ciKiFj2dxNtGfn/U2Y3djdWQ2bouIiLEj8xatn2vCkQ1o9MhaucxI/JHbs+WCnOJnoGflrkbpPRv0TJDStljB/icpQY24/g7+VlNN1IEm6Z2MiGo7fcI=
  on:
    tags: true
    branch: master
