language: python
python: 
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"


env: 
  - "TEST_SUITE=\"tests/uts\" -v"
  - "TEST_SUITE=\"tests/integration\" -v"
jobs: 
  include: 
    - name: "Unit Tests"
      script: "pytest $TEST_SUITE -v"

    - 
      name: "Integration Tests"
      script: "pytest $TEST_SUITE -v"

